### ISSUE TITLE
Wrap up!

### ISSUE THREAD

**Issue by joshuamabina** [chrisoemma/fakeCodes#8]
Hi @chrisoemma 

This is really good work.

Kindly help to:

- [x] In the name of uniformity, kindly rename your repo to **fake-codes**
- [x] Feel free to merge all your changes to the master branch. The GitHub is not a requirement for this challenge.

Appreciated.

**Comment by chrisoemma** [comment]
Thanks for your time to review my repo, I wanted to implement changes made by @BenMaruchu as well as learn more. I will rename my repo to fake-codes.
Appreciated
